[package]
name = "neutron-sdk"
description = "Neutron CosmWasm SDK for interacting with Neutron blockchain"
version = "0.11.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron-org/neutron-sdk"
homepage = "https://neutron.org"
readme = "README.md"

[dependencies]
cosmwasm-std = { workspace = true, features = ["cosmwasm_2_0"] }
cosmos-sdk-proto = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-cw-value = "0.7.0"
schemars = { workspace = true }
serde-json-wasm = { workspace = true }
bech32 = { workspace = true }
thiserror = { workspace = true }
protobuf = { workspace = true }
serde_json = { workspace = true }
cosmwasm-schema = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tendermint-proto = { workspace = true }
speedate = { workspace = true }
chrono = { version = "0.4.22", default-features = false }

[dev-dependencies]
base64 = { workspace = true }
prost-types = { workspace = true }
hex = { workspace = true }
